### ISSUE TITLE
채널 관리자 View

### ISSUE THREAD

**Issue by chaejin-jen** [42MVP/front-end#46]
## Task
설명 : 채널 역할(role)에 따른 뷰 변경

- [x] #61 
    - admin
      - [ ] 채널 유저 관리 모달
    - onwer
      - [ ] 채널 모드 변경 버튼 활성화
          - [ ] 채널 모드 변경에 따른 visible 버튼 변경
      - [x] 채널 유저 관리 모달 admin 버튼 활성화 #49

### Discussion
- 채널 권한(role) 확인 로직
  - API 호출 전에 권한 확인 (프론트에서도 막을건지)
